esphome:
  name: esp32

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "B5IDMzDWtZsz977xr1o2cBw8T8aFcvnIENLIdSFG/nY="

ota:
  password: "c505b9cf35497a67d2a6bb3bee77a775"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32 Fallback Hotspot"
    password: "9yRs9yinjDl3"

captive_portal:

sensor:
  - platform: ultrasonic
    trigger_pin: 18
    echo_pin: 5
    name: "Nível de água"
    update_interval: 0.5s
    id: sensor_watter
    on_value_range:
      below: 0.05
      then:
        - switch.turn_off:
            id: switch_pump
        - switch.turn_off:
            id: switch_coffee

  - platform: ultrasonic
    trigger_pin: 32 
    echo_pin: 35
    name: "Detector de xícara"
    update_interval: 0.5s
    id: sensor_cup
    
output:
  - platform: gpio
    pin: 25
    id: btn_request
    
  - platform: gpio
    pin: 26
    id: btn_add_cup
    
  - platform: gpio
    pin: 27
    id: btn_rem_cup

button:
  - platform: output
    name: "Pedir café"
    output: btn_request
    duration: 500ms
    
  - platform: output
    name: "Adicionar xícaras"
    output: btn_add_cup
    duration: 500ms
    
  - platform: output
    name: "Remover xícaras"
    output: btn_rem_cup
    duration: 500ms
    
    
binary_sensor:
  - platform: gpio
    pin: 25
    name: "Pedir café - Sensor"
    
  - platform: gpio
    pin: 26
    name: "Adicionar café - Sensor"
    
  - platform: gpio
    pin: 27
    name: "Remover xícara - Sensor"
    
number:
  - platform: template
    name: "Quantidade de xícaras"
    optimistic: true
    min_value: 0
    max_value: 30
    step: 1

switch:
  - platform: gpio
    pin: 2
    name: "Bomba"
    id: switch_pump
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: 12
    name: "Cafeteira"
    id: switch_coffee
    restore_mode: ALWAYS_OFF
    
text_sensor:
  - platform: homeassistant    
    name: "Display - linha 1"
    entity_id: input_text.display_line_1
    id: display_line_1
  - platform: homeassistant    
    name: "Display - linha 2"
    entity_id: input_text.display_line_2
    id: display_line_2

i2c:
  sda: 21
  scl: 22

display:
  - platform: lcd_pcf8574
    dimensions: 16x2
    address: 0x3F
    lambda: |-
      it.printf(0, 0, "%s",id(display_line_1).state.c_str());
      it.printf(0, 1, "%s",id(display_line_2).state.c_str());

interval:
  - interval: 1s
    then:
      if:
        condition:
          not:
            wifi.connected:
        then:
          - switch.turn_off: switch_pump
          - switch.turn_off: switch_coffee
